//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kafedra
    {
        public Kafedra()
        {
            this.Prepodavateli = new HashSet<Prepodavateli>();
        }
    
        public int ID_Kafedri { get; set; }
        public string Nazvanie_Kafedri { get; set; }
        public Nullable<int> ID_Faculteta { get; set; }
    
        public virtual Fakultet Fakultet { get; set; }
        public virtual ICollection<Prepodavateli> Prepodavateli { get; set; }
    }
}
