//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        public Predmet()
        {
            this.Tema = new HashSet<Tema>();
        }
    
        public int ID_Predmeta { get; set; }
        public string Nazvanie_Predmeta { get; set; }
    
        public virtual ICollection<Tema> Tema { get; set; }
    }
}
