//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tema
    {
        public Tema()
        {
            this.Tema1 = new HashSet<Tema>();
            this.Vopros = new HashSet<Vopros>();
        }
    
        public int ID_Temi { get; set; }
        public string Nazvanie_Temi { get; set; }
        public int ID_Predmeta { get; set; }
        public Nullable<int> ID_Nad_Tema { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual ICollection<Tema> Tema1 { get; set; }
        public virtual Tema Tema2 { get; set; }
        public virtual ICollection<Vopros> Vopros { get; set; }
    }
}
