//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_Voprosa
    {
        public Tip_Voprosa()
        {
            this.Vopros = new HashSet<Vopros>();
        }
    
        public int ID_Tipa { get; set; }
        public string Tip { get; set; }
    
        public virtual ICollection<Vopros> Vopros { get; set; }
    }
}
