//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vidi_Rabot
    {
        public Vidi_Rabot()
        {
            this.Zadanie = new HashSet<Zadanie>();
        }
    
        public int ID_Vida { get; set; }
        public string Nazvanie_Vida { get; set; }
    
        public virtual ICollection<Zadanie> Zadanie { get; set; }
    }
}
