//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vopros
    {
        public Vopros()
        {
            this.Otvet = new HashSet<Otvet>();
            this.Zadanie = new HashSet<Zadanie>();
        }
    
        public int ID_Voprosa { get; set; }
        public string Tekst_Voprosa { get; set; }
        public int ID_Tipa { get; set; }
        public int ID_Prepodavatelya { get; set; }
        public int ID_Temi { get; set; }
        public Nullable<int> Stoimost_Voprosa { get; set; }
    
        public virtual ICollection<Otvet> Otvet { get; set; }
        public virtual Prepodavateli Prepodavateli { get; set; }
        public virtual Tema Tema { get; set; }
        public virtual Tip_Voprosa Tip_Voprosa { get; set; }
        public virtual ICollection<Zadanie> Zadanie { get; set; }
    }
}
