//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadanie
    {
        public Zadanie()
        {
            this.Vopros = new HashSet<Vopros>();
        }
    
        public int ID_Raboti { get; set; }
        public Nullable<int> Kolichestvo_Voprosov { get; set; }
        public Nullable<int> Poluchennaya_Ocenka { get; set; }
        public int ID_Student { get; set; }
        public int ID_Vida { get; set; }
        public Nullable<System.DateTime> Data_Sdachi { get; set; }
        public Nullable<int> Stoimost_Raboti { get; set; }
        public Nullable<System.DateTime> Data_Vidachi { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Vidi_Rabot Vidi_Rabot { get; set; }
        public virtual ICollection<Vopros> Vopros { get; set; }
    }
}
